package uy.com.tmwc.facturator.libra.entity;


// Generated 11/06/2013 12:49:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoriasclientesPK generated by hbm2java
 */
@Embeddable
public class CategoriasclientesPK implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Column(name = "EmpId", nullable = false, length = 10)
	private String empId;

	@Column(name = "CategCliId", nullable = false, length = 3)
	private String categCliId;

	public CategoriasclientesPK() {
	}

	public CategoriasclientesPK(String empId, String categCliId) {
		this.empId = empId;
		this.categCliId = categCliId;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getCategCliId() {
		return this.categCliId;
	}

	public void setCategCliId(String categCliId) {
		this.categCliId = categCliId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoriasclientesPK))
			return false;
		CategoriasclientesPK castOther = (CategoriasclientesPK) other;

		return ((this.getEmpId() == castOther.getEmpId()) || (this.getEmpId() != null && castOther.getEmpId() != null && this.getEmpId().equals(castOther.getEmpId())))
				&& ((this.getCategCliId() == castOther.getCategCliId()) || (this.getCategCliId() != null && castOther.getCategCliId() != null && this.getCategCliId().equals(
						castOther.getCategCliId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmpId() == null ? 0 : this.getEmpId().hashCode());
		result = 37 * result + (getCategCliId() == null ? 0 : this.getCategCliId().hashCode());
		return result;
	}

}
